name: "Cachix"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  builds:
    name: Build configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v31
      with:
        install_url: https://releases.nixos.org/nix/nix-2.28.3/install
        extra_nix_config: |
          experimental-features = nix-command flakes pipe-operators
    - uses: cachix/cachix-action@v16
      with:
        name: jrestivo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build . -L
